- name: APIC - Leaf interface setup
  hosts: dCloud1
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: '{{ apic_host }}'
      username: '{{ apic_username }}'
      password: '{{ apic_password }}'
      use_proxy: '{{ apic_use_proxy }}'
      validate_certs: '{{ apic_validate_certs }}'
    template: "{{ lookup('file', 'group_vars/template.json') | from_json }}"

  
  tasks:
  - name: Add interface profiles and port block ranges for each leaf node pairs 
    aci_rest:
      <<: *aci_login
      path: /api/mo/uni.xml
      method: post
      content: |
        <infraInfra>
          {% for nodepair in switches.leaf.nodes %}
          <infraAccPortP name="Leaf{{ nodepair.sw1.nodeId }}_IntProf">
            {% for n in range(template[nodepair.template].endPort) %}
            <infraHPortS name="eth1_{{ n+1 }}" type="range">
              <infraPortBlk annotation="" descr="" fromCard="1" fromPort="{{ n+1 }}" name="blk" nameAlias="" toCard="1" toPort="{{ n+1 }}"/>
            </infraHPortS>
            {% endfor %}
          </infraAccPortP>
          <infraAccPortP name="Leaf{{ nodepair.sw2.nodeId }}_IntProf">
            {% for n in range(template[nodepair.template].endPort) %}
            <infraHPortS name="eth1_{{ n+1 }}" type="range">
              <infraPortBlk annotation="" descr="" fromCard="1" fromPort="{{ n+1 }}" name="blk" nameAlias="" toCard="1" toPort="{{ n+1 }}"/>
            </infraHPortS>
            {% endfor %}
          </infraAccPortP>
          {% endfor %}
        </infraInfra>
    delegate_to: localhost