- name: Test Workbook
  hosts: dCloud1
  gather_facts: no
  vars:
    template: "{{ lookup('file', 'group_vars/template.json') | from_json }}"

  tasks:
  - name: Test blog

    debug:
      msg: |
        {% for nodepair in switches.leaf.nodes %}
        {{ nodepair.vpc }}
        {% endfor %}
